# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Hitesh Bhardwaj, M.Sc.
description: >- # this means to ignore newlines until "baseurl:"
  Description of Hitesh Bhardwaj's education and background.
baseurl: "" # the subpath of the site
url: "https://hiteshbhardwaj14.github.io" # the base hostname & protocol for the site
# og_image: /assets/img/profile-pic.jpg
# google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Education
    - name: Projects
    - name: Publications
    - name: Awards

footer:
  show_powered_by: false
  contact:
    - name: Email
      value: hitesh_bhardwaj@mymail.sutd.edu.sg
      link: mailto:hitesh_bhardwaj@mymail.sutd.edu.sg

  follow:
    # - name: Twitter
    #   link: http://twitter.com/YourTwitterUsername
    #   username: "@YourTwitterUsername"
    - name: LinkedIn
      link: http://linkedin.com/in/hitesh-bhardwaj14
    - name: GitHub
      link: http://github.com/hiteshbhardwaj14

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed


# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
